python manage.py runscript insert-all-countries
python manage.py runscript add-flags-to-countries.py
#python manage.py runscript insert-all-theatres
python manage.py runscript insert-all-cemeteries
python manage.py runscript insert-all-pow-camps
python manage.py runscript insert-all-ranks
python manage.py runscript insert-all-decorations
python manage.py runscript insert-all-companies
python manage.py runscript insert-all-soldiers
python manage.py runscript insert-all-soldier-imprisonments
python manage.py runscript insert-all-soldier-deaths
#python manage.py runscript insert-all-soldier-decorations
