# Generated by Django 4.2.7 on 2023-11-17 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255, unique=True)),
                ("notes", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255, unique=True)),
                ("alpha2", models.CharField(default="", max_length=2, unique=True)),
                ("alpha3", models.CharField(default="", max_length=3, unique=True)),
                ("country_number", models.CharField(max_length=3, unique=True)),
                ("flag", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PowCamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255, unique=True)),
                ("nearest_city", models.CharField(default="", max_length=255)),
                ("notes", models.CharField(default="", max_length=255)),
                ("wartime_country", models.CharField(default="", max_length=255)),
                ("latitude", models.CharField(default="", max_length=255)),
                ("longitude", models.CharField(default="", max_length=255)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="powcamps",
                        to="cmp.country",
                        to_field="country_number",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("abbreviation", models.CharField(blank=True, max_length=50)),
                (
                    "rank_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OR", "Other Rank"),
                            ("NC", "Non Commisioned Officer"),
                            ("OF", "Officer"),
                        ],
                        default="Other Rank",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Soldier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(default="", max_length=255)),
                ("initials", models.CharField(default="", max_length=255)),
                ("army_number", models.CharField(default="", max_length=255)),
                ("notes", models.CharField(default="", max_length=255)),
                (
                    "rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranks",
                        to="cmp.rank",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Theatre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SoldierImprisonment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_company", models.CharField(default="", max_length=255)),
                ("pow_number", models.CharField(default="", max_length=255)),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                ("legacy_date_from", models.CharField(default="", max_length=255)),
                ("legacy_date_to", models.CharField(default="", max_length=255)),
                ("notes", models.CharField(default="", max_length=255)),
                (
                    "pow_camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cmp.powcamp"
                    ),
                ),
                (
                    "soldier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cmp.soldier"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoldierDecoration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255, unique=True)),
                ("notes", models.CharField(default="", max_length=255)),
                ("details_link", models.CharField(default="", max_length=255)),
                ("abbreviation", models.CharField(default="", max_length=255)),
                (
                    "country_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cmp.country"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Decoration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255, unique=True)),
                ("notes", models.CharField(default="", max_length=255)),
                ("details_link", models.CharField(default="", max_length=255)),
                ("abbreviation", models.CharField(default="", max_length=255)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cmp.country"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cemetery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255, unique=True)),
                ("latitude", models.CharField(default="", max_length=255)),
                ("longitude", models.CharField(default="", max_length=255)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cemeteries",
                        to="cmp.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
    ]
