# Generated by Django 4.2.5 on 2023-10-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("old_id", models.IntegerField(blank=True, null=True)),
                ("alpha2", models.CharField(max_length=2)),
                ("alpha3", models.CharField(max_length=3)),
            ],
        ),
    ]
