# Generated by Django 4.2.5 on 2023-11-03 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cemetery",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cemeteries",
                to="cmp.country",
                to_field="CountryNumber",
            ),
        ),
    ]
