# Generated by Django 4.2.5 on 2023-10-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0002_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="alpha2",
        ),
        migrations.RemoveField(
            model_name="country",
            name="alpha3",
        ),
        migrations.RemoveField(
            model_name="country",
            name="name",
        ),
        migrations.RemoveField(
            model_name="country",
            name="old_id",
        ),
        migrations.AddField(
            model_name="country",
            name="alt_spellings",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="area",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="country",
            name="borders",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="callingCodes",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="capital",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="cca2",
            field=models.CharField(default="", max_length=2, unique=True),
        ),
        migrations.AddField(
            model_name="country",
            name="cca3",
            field=models.CharField(default="", max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name="country",
            name="ccn3",
            field=models.CharField(default="", max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name="country",
            name="cioc",
            field=models.CharField(default="", max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name="country",
            name="currencies",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="demonyms_eng_f",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="demonyms_eng_m",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="demonyms_fra_f",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="demonyms_fra_m",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="flag",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="idd_root",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="country",
            name="idd_suffixes",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="independent",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="country",
            name="landlocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="country",
            name="languages",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="latlng",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="name_common",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="country",
            name="name_official",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="country",
            name="region",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="status",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="subregion",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="tld",
            field=models.CharField(default="", max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_ces_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_ces_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_deu_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_deu_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_est_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_est_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_fin_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_fin_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_fra_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_fra_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_hrv_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_hrv_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_hun_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_hun_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_ita_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_ita_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_jpn_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_jpn_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_kor_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_kor_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_nld_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_nld_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_per_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_per_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_pol_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_pol_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_por_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_por_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_rus_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_rus_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_slk_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_slk_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_spa_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_spa_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_swe_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_swe_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_urd_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_urd_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_zho_common",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="translations_zho_official",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="unMember",
            field=models.BooleanField(default=True),
        ),
    ]
