# Generated by Django 4.2.5 on 2023-10-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0006_alter_country_name_official"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name_common",
            field=models.CharField(default="", max_length=255),
        ),
    ]
