# Generated by Django 4.2.5 on 2023-10-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0007_alter_country_name_common"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="ccn3",
            field=models.CharField(default="", max_length=3),
        ),
    ]
