# Generated by Django 4.2.5 on 2023-10-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0008_alter_country_ccn3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="ccn3",
            field=models.CharField(default="", max_length=3, unique=True),
        ),
    ]
