# Generated by Django 4.2.5 on 2023-10-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0009_alter_country_ccn3"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50, unique=True)),
                ("Abbr", models.CharField(blank=True, max_length=50)),
                (
                    "Class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OR", "Other Rank"),
                            ("NC", "Non Commisioned Officer"),
                            ("OF", "Officer"),
                        ],
                        default="Other Rank",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
