# Generated by Django 4.2.5 on 2023-11-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0012_company_theatre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rank",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
